version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nolintlint
    - unconvert
    - usestdlibvars
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
