//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ActualState.
const (
	ActualStateFailed     ActualState = "failed"
	ActualStateRestarting ActualState = "restarting"
	ActualStateRunning    ActualState = "running"
	ActualStateStarting   ActualState = "starting"
	ActualStateStopped    ActualState = "stopped"
	ActualStateStopping   ActualState = "stopping"
	ActualStateUnknown    ActualState = "unknown"
)

// Valid indicates whether the value is a known member of the ActualState enum.
func (e ActualState) Valid() bool {
	switch e {
	case ActualStateFailed:
		return true
	case ActualStateRestarting:
		return true
	case ActualStateRunning:
		return true
	case ActualStateStarting:
		return true
	case ActualStateStopped:
		return true
	case ActualStateStopping:
		return true
	case ActualStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for DesiredState.
const (
	DesiredStateRunning DesiredState = "running"
	DesiredStateStopped DesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the DesiredState enum.
func (e DesiredState) Valid() bool {
	switch e {
	case DesiredStateRunning:
		return true
	case DesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyExists       ErrorCode = "already_exists"
	ErrorCodeForbidden           ErrorCode = "forbidden"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidArgument     ErrorCode = "invalid_argument"
	ErrorCodeNotFound            ErrorCode = "not_found"
	ErrorCodeOperationInProgress ErrorCode = "operation_in_progress"
	ErrorCodePortInUse           ErrorCode = "port_in_use"
	ErrorCodeServerRunning       ErrorCode = "server_running"
	ErrorCodeServerStarting      ErrorCode = "server_starting"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAlreadyExists:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidArgument:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeOperationInProgress:
		return true
	case ErrorCodePortInUse:
		return true
	case ErrorCodeServerRunning:
		return true
	case ErrorCodeServerStarting:
		return true
	default:
		return false
	}
}

// Defines values for Health.
const (
	HealthHealthy   Health = "healthy"
	HealthNone      Health = "none"
	HealthStarting  Health = "starting"
	HealthUnhealthy Health = "unhealthy"
)

// Valid indicates whether the value is a known member of the Health enum.
func (e Health) Valid() bool {
	switch e {
	case HealthHealthy:
		return true
	case HealthNone:
		return true
	case HealthStarting:
		return true
	case HealthUnhealthy:
		return true
	default:
		return false
	}
}

// Defines values for LogEntrySource.
const (
	LogEntrySourceContainer LogEntrySource = "container"
	LogEntrySourceSystemd   LogEntrySource = "systemd"
)

// Valid indicates whether the value is a known member of the LogEntrySource enum.
func (e LogEntrySource) Valid() bool {
	switch e {
	case LogEntrySourceContainer:
		return true
	case LogEntrySourceSystemd:
		return true
	default:
		return false
	}
}

// Defines values for OperationKind.
const (
	OperationKindDown OperationKind = "down"
	OperationKindUp   OperationKind = "up"
)

// Valid indicates whether the value is a known member of the OperationKind enum.
func (e OperationKind) Valid() bool {
	switch e {
	case OperationKindDown:
		return true
	case OperationKindUp:
		return true
	default:
		return false
	}
}

// Defines values for OperationResult.
const (
	OperationResultFailed     OperationResult = "failed"
	OperationResultInProgress OperationResult = "in_progress"
	OperationResultSucceeded  OperationResult = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationResult enum.
func (e OperationResult) Valid() bool {
	switch e {
	case OperationResultFailed:
		return true
	case OperationResultInProgress:
		return true
	case OperationResultSucceeded:
		return true
	default:
		return false
	}
}

// ActualState systemd の unit の状態を読み替えたもの。
// inactive → stopped、activating/start → starting、active/running → running、
// deactivating → stopping、activating/auto-restart → restarting、failed → failed。
// unit の状態を取得できなかった場合は unknown。
type ActualState string

// CreateServerRequest defines model for CreateServerRequest.
type CreateServerRequest struct {
	// AcceptEula Minecraft の EULA に同意する。true でなければ 400
	AcceptEula bool               `json:"acceptEula"`
	Env        *map[string]string `json:"env,omitempty"`
	ImageTag   *string            `json:"imageTag,omitempty"`

	// Memory JVM のヒープ。コンテナのメモリ上限はここから自動で計算する
	//
	// Example: 2G
	Memory *Memory `json:"memory,omitempty"`

	// Name Example: survival
	Name    ServerName `json:"name"`
	Port    int        `json:"port"`
	Type    *string    `json:"type,omitempty"`
	Version *string    `json:"version,omitempty"`
}

// DesiredState defines model for DesiredState.
type DesiredState string

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code invalid_argument: 入力の検証エラー（400）
	// forbidden: mcctl グループのメンバーではない（403）
	// not_found: サーバーがない（404）
	// already_exists: 同じ名前のサーバーがある（409）
	// port_in_use: 他のサーバーとポートが重複している（409）
	// operation_in_progress: 同じサーバーへの操作を実行中（409）
	// server_running: 動いているサーバーは削除できない（409）
	// server_starting: 起動処理の途中。force で強行できる（409）
	// internal: その他（500）
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode invalid_argument: 入力の検証エラー（400）
// forbidden: mcctl グループのメンバーではない（403）
// not_found: サーバーがない（404）
// already_exists: 同じ名前のサーバーがある（409）
// port_in_use: 他のサーバーとポートが重複している（409）
// operation_in_progress: 同じサーバーへの操作を実行中（409）
// server_running: 動いているサーバーは削除できない（409）
// server_starting: 起動処理の途中。force で強行できる（409）
// internal: その他（500）
type ErrorCode string

// Health コンテナの healthcheck の結果。コンテナがない場合は none
type Health string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	Message string `json:"message"`

	// Source container はマイクラ（コンテナ）の出力、systemd は unit の起動・停止・再起動の記録
	Source LogEntrySource `json:"source"`
	Time   time.Time      `json:"time"`
}

// LogEntrySource container はマイクラ（コンテナ）の出力、systemd は unit の起動・停止・再起動の記録
type LogEntrySource string

// Memory JVM のヒープ。コンテナのメモリ上限はここから自動で計算する
//
// Example: 2G
type Memory = string

// Operation デーモンがメモリに持つ最後の操作。デーモンを再起動すると消える
type Operation struct {
	// Error result が failed のときの理由
	Error      *string         `json:"error,omitempty"`
	FinishedAt *time.Time      `json:"finishedAt,omitempty"`
	Kind       OperationKind   `json:"kind"`
	Result     OperationResult `json:"result"`
	StartedAt  time.Time       `json:"startedAt"`
}

// OperationKind defines model for Operation.Kind.
type OperationKind string

// OperationResult defines model for Operation.Result.
type OperationResult string

// Server defines model for Server.
type Server struct {
	DesiredState DesiredState `json:"desiredState"`

	// LastOperation デーモンがメモリに持つ最後の操作。デーモンを再起動すると消える
	LastOperation *Operation `json:"lastOperation,omitempty"`

	// Spec サーバーの定義。Store に保存される
	Spec   ServerSpec `json:"spec"`
	Status Status     `json:"status"`
}

// ServerList defines model for ServerList.
type ServerList struct {
	Servers []Server `json:"servers"`
}

// ServerName Example: survival
type ServerName = string

// ServerSpec サーバーの定義。Store に保存される
type ServerSpec struct {
	// Env itzg に渡す任意の環境変数。専用のフィールドと重なった場合は専用のフィールドが優先される
	Env map[string]string `json:"env"`

	// ImageTag itzg/minecraft-server のタグ。Java のバージョン選択に使う
	//
	// Example: java21
	ImageTag string `json:"imageTag"`

	// Memory JVM のヒープ。コンテナのメモリ上限はここから自動で計算する
	//
	// Example: 2G
	Memory Memory `json:"memory"`

	// Name Example: survival
	Name ServerName `json:"name"`

	// Port Example: 25565
	Port int `json:"port"`

	// Type itzg の TYPE。値の検証はイメージに任せる
	//
	// Example: PAPER
	Type string `json:"type"`

	// Version itzg の VERSION
	//
	// Example: 1.21.4
	Version string `json:"version"`
}

// Status defines model for Status.
type Status struct {
	// Health コンテナの healthcheck の結果。コンテナがない場合は none
	Health Health `json:"health"`

	// Restarts systemd の NRestarts
	Restarts int `json:"restarts"`

	// State systemd の unit の状態を読み替えたもの。
	// inactive → stopped、activating/start → starting、active/running → running、
	// deactivating → stopping、activating/auto-restart → restarting、failed → failed。
	// unit の状態を取得できなかった場合は unknown。
	State ActualState `json:"state"`
}

// Name Example: survival
type Name = ServerName

// DeleteServerParams defines parameters for DeleteServer.
type DeleteServerParams struct {
	// Purge データディレクトリと drop-in も削除する
	Purge *bool `form:"purge,omitempty" json:"purge,omitempty"`
}

// DownServerParams defines parameters for DownServer.
type DownServerParams struct {
	// Force 起動処理の途中でも停止する（最大 60 秒後に SIGKILL される）
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// GetServerLogsParams defines parameters for GetServerLogs.
type GetServerLogsParams struct {
	Follow *bool `form:"follow,omitempty" json:"follow,omitempty"`

	// Tail 末尾から何件返すか。省略時はすべて
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`
}

// UpServerParams defines parameters for UpServer.
type UpServerParams struct {
	// Pull イメージが手元にあっても pull する
	Pull *bool `form:"pull,omitempty" json:"pull,omitempty"`
}

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServerRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListServers サーバーの一覧
	//
	// Corresponds with GET /servers (the `ListServers` operationId).
	ListServers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateServerWithBody サーバーを登録し、データディレクトリを作る
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /servers (the `CreateServer` operationId).
	CreateServerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateServer サーバーを登録し、データディレクトリを作る
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /servers (the `CreateServer` operationId).
	CreateServer(ctx context.Context, body CreateServerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteServer サーバーを削除する（rm）
	//
	// Corresponds with DELETE /servers/{name} (the `DeleteServer` operationId).
	DeleteServer(ctx context.Context, name Name, params *DeleteServerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServer サーバーの詳細（status）
	//
	// Corresponds with GET /servers/{name} (the `GetServer` operationId).
	GetServer(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownServer サーバーを停止する（非同期）
	//
	// Corresponds with POST /servers/{name}/down (the `DownServer` operationId).
	DownServer(ctx context.Context, name Name, params *DownServerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServerLogs サーバーのログ（journal）を読む
	//
	// LogEntry を 1 行に 1 件ずつ流す（NDJSON）。停止中のサーバーでも過去のログを読める。
	// follow=true のときは、クライアントが切断するまで新しいログを流し続ける。
	//
	// Corresponds with GET /servers/{name}/logs (the `GetServerLogs` operationId).
	GetServerLogs(ctx context.Context, name Name, params *GetServerLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpServer サーバーを起動する（非同期）
	//
	// Corresponds with POST /servers/{name}/up (the `UpServer` operationId).
	UpServer(ctx context.Context, name Name, params *UpServerParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListServers サーバーの一覧
//
// Corresponds with GET /servers (the `ListServers` operationId).
func (c *Client) ListServers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListServersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateServerWithBody サーバーを登録し、データディレクトリを作る
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /servers (the `CreateServer` operationId).
func (c *Client) CreateServerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServerRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateServer サーバーを登録し、データディレクトリを作る
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /servers (the `CreateServer` operationId).
func (c *Client) CreateServer(ctx context.Context, body CreateServerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServerRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteServer サーバーを削除する（rm）
//
// Corresponds with DELETE /servers/{name} (the `DeleteServer` operationId).
func (c *Client) DeleteServer(ctx context.Context, name Name, params *DeleteServerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteServerRequest(c.Server, name, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetServer サーバーの詳細（status）
//
// Corresponds with GET /servers/{name} (the `GetServer` operationId).
func (c *Client) GetServer(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DownServer サーバーを停止する（非同期）
//
// Corresponds with POST /servers/{name}/down (the `DownServer` operationId).
func (c *Client) DownServer(ctx context.Context, name Name, params *DownServerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownServerRequest(c.Server, name, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetServerLogs サーバーのログ（journal）を読む
//
// LogEntry を 1 行に 1 件ずつ流す（NDJSON）。停止中のサーバーでも過去のログを読める。
// follow=true のときは、クライアントが切断するまで新しいログを流し続ける。
//
// Corresponds with GET /servers/{name}/logs (the `GetServerLogs` operationId).
func (c *Client) GetServerLogs(ctx context.Context, name Name, params *GetServerLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerLogsRequest(c.Server, name, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpServer サーバーを起動する（非同期）
//
// Corresponds with POST /servers/{name}/up (the `UpServer` operationId).
func (c *Client) UpServer(ctx context.Context, name Name, params *UpServerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpServerRequest(c.Server, name, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListServersRequest constructs an http.Request for the ListServers method
func NewListServersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateServerRequest calls the generic CreateServer builder with application/json body
func NewCreateServerRequest(server string, body CreateServerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateServerRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateServerRequestWithBody constructs an http.Request for the CreateServer method, with any body, and a specified content type
func NewCreateServerRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteServerRequest constructs an http.Request for the DeleteServer method
func NewDeleteServerRequest(server string, name Name, params *DeleteServerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Purge != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "purge", *params.Purge, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServerRequest constructs an http.Request for the GetServer method
func NewGetServerRequest(server string, name Name) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownServerRequest constructs an http.Request for the DownServer method
func NewDownServerRequest(server string, name Name, params *DownServerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers/%s/down", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Force != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "force", *params.Force, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServerLogsRequest constructs an http.Request for the GetServerLogs method
func NewGetServerLogsRequest(server string, name Name, params *GetServerLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Follow != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "follow", *params.Follow, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Tail != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tail", *params.Tail, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpServerRequest constructs an http.Request for the UpServer method
func NewUpServerRequest(server string, name Name, params *UpServerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/servers/%s/up", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Pull != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pull", *params.Pull, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListServersWithResponse サーバーの一覧
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /servers (the `ListServers` operationId).
	ListServersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListServersResponse, error)

	// CreateServerWithBodyWithResponse サーバーを登録し、データディレクトリを作る
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /servers (the `CreateServer` operationId).
	CreateServerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServerResponse, error)

	// CreateServerWithResponse サーバーを登録し、データディレクトリを作る
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /servers (the `CreateServer` operationId).
	CreateServerWithResponse(ctx context.Context, body CreateServerJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServerResponse, error)

	// DeleteServerWithResponse サーバーを削除する（rm）
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /servers/{name} (the `DeleteServer` operationId).
	DeleteServerWithResponse(ctx context.Context, name Name, params *DeleteServerParams, reqEditors ...RequestEditorFn) (*DeleteServerResponse, error)

	// GetServerWithResponse サーバーの詳細（status）
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /servers/{name} (the `GetServer` operationId).
	GetServerWithResponse(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*GetServerResponse, error)

	// DownServerWithResponse サーバーを停止する（非同期）
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /servers/{name}/down (the `DownServer` operationId).
	DownServerWithResponse(ctx context.Context, name Name, params *DownServerParams, reqEditors ...RequestEditorFn) (*DownServerResponse, error)

	// GetServerLogsWithResponse サーバーのログ（journal）を読む
	//
	// LogEntry を 1 行に 1 件ずつ流す（NDJSON）。停止中のサーバーでも過去のログを読める。
	// follow=true のときは、クライアントが切断するまで新しいログを流し続ける。
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /servers/{name}/logs (the `GetServerLogs` operationId).
	GetServerLogsWithResponse(ctx context.Context, name Name, params *GetServerLogsParams, reqEditors ...RequestEditorFn) (*GetServerLogsResponse, error)

	// UpServerWithResponse サーバーを起動する（非同期）
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /servers/{name}/up (the `UpServer` operationId).
	UpServerWithResponse(ctx context.Context, name Name, params *UpServerParams, reqEditors ...RequestEditorFn) (*UpServerResponse, error)
}

type ListServersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ServerList
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListServersResponse) GetJSON200() *ServerList {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListServersResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListServersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListServersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListServersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListServersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Server
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateServerResponse) GetJSON201() *Server {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateServerResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreateServerResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateServerResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CreateServerResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CreateServerResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteServerResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteServerResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteServerResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteServerResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteServerResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Server
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetServerResponse) GetJSON200() *Server {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetServerResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetServerResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetServerResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DownServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *Server
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r DownServerResponse) GetJSON202() *Server {
	return r.JSON202
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DownServerResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DownServerResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DownServerResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DownServerResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DownServerResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DownServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DownServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServerLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetServerLogsResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetServerLogsResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetServerLogsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetServerLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServerLogsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *Server
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r UpServerResponse) GetJSON202() *Server {
	return r.JSON202
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpServerResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpServerResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpServerResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UpServerResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UpServerResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListServersWithResponse サーバーの一覧
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /servers (the `ListServers` operationId).
func (c *ClientWithResponses) ListServersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListServersResponse, error) {
	rsp, err := c.ListServers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListServersResponse(rsp)
}

// CreateServerWithBodyWithResponse サーバーを登録し、データディレクトリを作る
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /servers (the `CreateServer` operationId).
func (c *ClientWithResponses) CreateServerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServerResponse, error) {
	rsp, err := c.CreateServerWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServerResponse(rsp)
}

// CreateServerWithResponse サーバーを登録し、データディレクトリを作る
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /servers (the `CreateServer` operationId).
func (c *ClientWithResponses) CreateServerWithResponse(ctx context.Context, body CreateServerJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServerResponse, error) {
	rsp, err := c.CreateServer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServerResponse(rsp)
}

// DeleteServerWithResponse サーバーを削除する（rm）
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /servers/{name} (the `DeleteServer` operationId).
func (c *ClientWithResponses) DeleteServerWithResponse(ctx context.Context, name Name, params *DeleteServerParams, reqEditors ...RequestEditorFn) (*DeleteServerResponse, error) {
	rsp, err := c.DeleteServer(ctx, name, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteServerResponse(rsp)
}

// GetServerWithResponse サーバーの詳細（status）
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /servers/{name} (the `GetServer` operationId).
func (c *ClientWithResponses) GetServerWithResponse(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*GetServerResponse, error) {
	rsp, err := c.GetServer(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerResponse(rsp)
}

// DownServerWithResponse サーバーを停止する（非同期）
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /servers/{name}/down (the `DownServer` operationId).
func (c *ClientWithResponses) DownServerWithResponse(ctx context.Context, name Name, params *DownServerParams, reqEditors ...RequestEditorFn) (*DownServerResponse, error) {
	rsp, err := c.DownServer(ctx, name, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownServerResponse(rsp)
}

// GetServerLogsWithResponse サーバーのログ（journal）を読む
//
// LogEntry を 1 行に 1 件ずつ流す（NDJSON）。停止中のサーバーでも過去のログを読める。
// follow=true のときは、クライアントが切断するまで新しいログを流し続ける。
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /servers/{name}/logs (the `GetServerLogs` operationId).
func (c *ClientWithResponses) GetServerLogsWithResponse(ctx context.Context, name Name, params *GetServerLogsParams, reqEditors ...RequestEditorFn) (*GetServerLogsResponse, error) {
	rsp, err := c.GetServerLogs(ctx, name, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerLogsResponse(rsp)
}

// UpServerWithResponse サーバーを起動する（非同期）
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /servers/{name}/up (the `UpServer` operationId).
func (c *ClientWithResponses) UpServerWithResponse(ctx context.Context, name Name, params *UpServerParams, reqEditors ...RequestEditorFn) (*UpServerResponse, error) {
	rsp, err := c.UpServer(ctx, name, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpServerResponse(rsp)
}

// ParseListServersResponse parses an HTTP response from a ListServersWithResponse call
func ParseListServersResponse(rsp *http.Response) (*ListServersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListServersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServerList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateServerResponse parses an HTTP response from a CreateServerWithResponse call
func ParseCreateServerResponse(rsp *http.Response) (*CreateServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Server
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteServerResponse parses an HTTP response from a DeleteServerWithResponse call
func ParseDeleteServerResponse(rsp *http.Response) (*DeleteServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetServerResponse parses an HTTP response from a GetServerWithResponse call
func ParseGetServerResponse(rsp *http.Response) (*GetServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Server
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDownServerResponse parses an HTTP response from a DownServerWithResponse call
func ParseDownServerResponse(rsp *http.Response) (*DownServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Server
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetServerLogsResponse parses an HTTP response from a GetServerLogsWithResponse call
func ParseGetServerLogsResponse(rsp *http.Response) (*GetServerLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpServerResponse parses an HTTP response from a UpServerWithResponse call
func ParseUpServerResponse(rsp *http.Response) (*UpServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Server
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListServers サーバーの一覧
	// (GET /servers)
	ListServers(w http.ResponseWriter, r *http.Request)
	// CreateServer サーバーを登録し、データディレクトリを作る
	// (POST /servers)
	CreateServer(w http.ResponseWriter, r *http.Request)
	// DeleteServer サーバーを削除する（rm）
	// (DELETE /servers/{name})
	DeleteServer(w http.ResponseWriter, r *http.Request, name Name, params DeleteServerParams)
	// GetServer サーバーの詳細（status）
	// (GET /servers/{name})
	GetServer(w http.ResponseWriter, r *http.Request, name Name)
	// DownServer サーバーを停止する（非同期）
	// (POST /servers/{name}/down)
	DownServer(w http.ResponseWriter, r *http.Request, name Name, params DownServerParams)
	// GetServerLogs サーバーのログ（journal）を読む
	// (GET /servers/{name}/logs)
	GetServerLogs(w http.ResponseWriter, r *http.Request, name Name, params GetServerLogsParams)
	// UpServer サーバーを起動する（非同期）
	// (POST /servers/{name}/up)
	UpServer(w http.ResponseWriter, r *http.Request, name Name, params UpServerParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListServers operation middleware
func (siw *ServerInterfaceWrapper) ListServers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateServer operation middleware
func (siw *ServerInterfaceWrapper) CreateServer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateServer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteServerParams

	// ------------- Optional query parameter "purge" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "purge", r.URL.Query(), &params.Purge, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "purge"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "purge", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteServer(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServer operation middleware
func (siw *ServerInterfaceWrapper) GetServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServer(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownServer operation middleware
func (siw *ServerInterfaceWrapper) DownServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownServerParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force", r.URL.Query(), &params.Force, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownServer(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServerLogs operation middleware
func (siw *ServerInterfaceWrapper) GetServerLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServerLogsParams

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tail", r.URL.Query(), &params.Tail, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tail"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tail", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServerLogs(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpServer operation middleware
func (siw *ServerInterfaceWrapper) UpServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpServerParams

	// ------------- Optional query parameter "pull" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pull", r.URL.Query(), &params.Pull, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pull"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pull", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpServer(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/servers", wrapper.ListServers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/servers", wrapper.CreateServer)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/servers/{name}", wrapper.DeleteServer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/servers/{name}", wrapper.GetServer)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/servers/{name}/up", wrapper.UpServer)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/servers/{name}/down", wrapper.DownServer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/servers/{name}/logs", wrapper.GetServerLogs)

	return m
}

type ErrorJSONResponse Error

type ListServersRequestObject struct {
}

type ListServersResponseObject interface {
	VisitListServersResponse(w http.ResponseWriter) error
}

type ListServers200JSONResponse ServerList

func (response ListServers200JSONResponse) VisitListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListServersdefaultJSONResponse) VisitListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServerRequestObject struct {
	Body *CreateServerJSONRequestBody
}

type CreateServerResponseObject interface {
	VisitCreateServerResponse(w http.ResponseWriter) error
}

type CreateServer201JSONResponse Server

func (response CreateServer201JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer400JSONResponse struct{ ErrorJSONResponse }

func (response CreateServer400JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer403JSONResponse Error

func (response CreateServer403JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer409JSONResponse Error

func (response CreateServer409JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateServerdefaultJSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServerRequestObject struct {
	Name   Name `json:"name"`
	Params DeleteServerParams
}

type DeleteServerResponseObject interface {
	VisitDeleteServerResponse(w http.ResponseWriter) error
}

type DeleteServer204Response struct {
}

func (response DeleteServer204Response) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteServer403JSONResponse struct{ ErrorJSONResponse }

func (response DeleteServer403JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServer404JSONResponse Error

func (response DeleteServer404JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServer409JSONResponse Error

func (response DeleteServer409JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteServerdefaultJSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetServerRequestObject struct {
	Name Name `json:"name"`
}

type GetServerResponseObject interface {
	VisitGetServerResponse(w http.ResponseWriter) error
}

type GetServer200JSONResponse Server

func (response GetServer200JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServer404JSONResponse struct{ ErrorJSONResponse }

func (response GetServer404JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetServerdefaultJSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DownServerRequestObject struct {
	Name   Name `json:"name"`
	Params DownServerParams
}

type DownServerResponseObject interface {
	VisitDownServerResponse(w http.ResponseWriter) error
}

type DownServer202JSONResponse Server

func (response DownServer202JSONResponse) VisitDownServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DownServer403JSONResponse struct{ ErrorJSONResponse }

func (response DownServer403JSONResponse) VisitDownServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DownServer404JSONResponse Error

func (response DownServer404JSONResponse) VisitDownServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownServer409JSONResponse Error

func (response DownServer409JSONResponse) VisitDownServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DownServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DownServerdefaultJSONResponse) VisitDownServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetServerLogsRequestObject struct {
	Name   Name `json:"name"`
	Params GetServerLogsParams
}

type GetServerLogsResponseObject interface {
	VisitGetServerLogsResponse(w http.ResponseWriter) error
}

type GetServerLogs200ApplicationxNdjsonResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetServerLogs200ApplicationxNdjsonResponse) VisitGetServerLogsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-ndjson")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type GetServerLogs404JSONResponse struct{ ErrorJSONResponse }

func (response GetServerLogs404JSONResponse) VisitGetServerLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetServerLogsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetServerLogsdefaultJSONResponse) VisitGetServerLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpServerRequestObject struct {
	Name   Name `json:"name"`
	Params UpServerParams
}

type UpServerResponseObject interface {
	VisitUpServerResponse(w http.ResponseWriter) error
}

type UpServer202JSONResponse Server

func (response UpServer202JSONResponse) VisitUpServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type UpServer403JSONResponse struct{ ErrorJSONResponse }

func (response UpServer403JSONResponse) VisitUpServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpServer404JSONResponse Error

func (response UpServer404JSONResponse) VisitUpServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpServer409JSONResponse Error

func (response UpServer409JSONResponse) VisitUpServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpServerdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpServerdefaultJSONResponse) VisitUpServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListServers サーバーの一覧
	// (GET /servers)
	ListServers(ctx context.Context, request ListServersRequestObject) (ListServersResponseObject, error)
	// CreateServer サーバーを登録し、データディレクトリを作る
	// (POST /servers)
	CreateServer(ctx context.Context, request CreateServerRequestObject) (CreateServerResponseObject, error)
	// DeleteServer サーバーを削除する（rm）
	// (DELETE /servers/{name})
	DeleteServer(ctx context.Context, request DeleteServerRequestObject) (DeleteServerResponseObject, error)
	// GetServer サーバーの詳細（status）
	// (GET /servers/{name})
	GetServer(ctx context.Context, request GetServerRequestObject) (GetServerResponseObject, error)
	// DownServer サーバーを停止する（非同期）
	// (POST /servers/{name}/down)
	DownServer(ctx context.Context, request DownServerRequestObject) (DownServerResponseObject, error)
	// GetServerLogs サーバーのログ（journal）を読む
	// (GET /servers/{name}/logs)
	GetServerLogs(ctx context.Context, request GetServerLogsRequestObject) (GetServerLogsResponseObject, error)
	// UpServer サーバーを起動する（非同期）
	// (POST /servers/{name}/up)
	UpServer(ctx context.Context, request UpServerRequestObject) (UpServerResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListServers operation middleware
func (sh *strictHandler) ListServers(w http.ResponseWriter, r *http.Request) {
	var request ListServersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListServers(ctx, request.(ListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListServersResponseObject); ok {
		if err := validResponse.VisitListServersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServer operation middleware
func (sh *strictHandler) CreateServer(w http.ResponseWriter, r *http.Request) {
	var request CreateServerRequestObject

	var body CreateServerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServer(ctx, request.(CreateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateServerResponseObject); ok {
		if err := validResponse.VisitCreateServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteServer operation middleware
func (sh *strictHandler) DeleteServer(w http.ResponseWriter, r *http.Request, name Name, params DeleteServerParams) {
	var request DeleteServerRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteServer(ctx, request.(DeleteServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteServerResponseObject); ok {
		if err := validResponse.VisitDeleteServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServer operation middleware
func (sh *strictHandler) GetServer(w http.ResponseWriter, r *http.Request, name Name) {
	var request GetServerRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetServer(ctx, request.(GetServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServerResponseObject); ok {
		if err := validResponse.VisitGetServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownServer operation middleware
func (sh *strictHandler) DownServer(w http.ResponseWriter, r *http.Request, name Name, params DownServerParams) {
	var request DownServerRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownServer(ctx, request.(DownServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownServerResponseObject); ok {
		if err := validResponse.VisitDownServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServerLogs operation middleware
func (sh *strictHandler) GetServerLogs(w http.ResponseWriter, r *http.Request, name Name, params GetServerLogsParams) {
	var request GetServerLogsRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetServerLogs(ctx, request.(GetServerLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServerLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServerLogsResponseObject); ok {
		if err := validResponse.VisitGetServerLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpServer operation middleware
func (sh *strictHandler) UpServer(w http.ResponseWriter, r *http.Request, name Name, params UpServerParams) {
	var request UpServerRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpServer(ctx, request.(UpServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpServer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpServerResponseObject); ok {
		if err := validResponse.VisitUpServerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
