package daemon

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/takiren/mcupdown/internal/engine"
	"github.com/takiren/mcupdown/internal/store"
)

// ErrNotRootless は podman が rootless で動いていないことを表す。mcctld は rootless podman 専用。
var ErrNotRootless = errors.New("podman is not running rootless")

// Sync はデーモンの起動時に、Store と systemd の状態を揃える。リクエストを受け付ける前に呼ぶ。
//
// ホストの再起動後の自動起動とクラッシュからの復旧は systemd が担うので、ここでは最小限のことだけを行う。
//   - podman が rootless でなければ ErrNotRootless を返す（デーモンは起動をやめる）
//   - Store のすべてのサーバーについて .container を生成し直し、変わっていれば daemon-reload する
//   - 求める状態が running なのに unit が止まっていれば起動する（ファイルを書いた直後にデーモンが落ちた場合など）。
//     failed はそのままにして status で見せる
//   - mcctld が生成したのに Store にない .container は、警告を出すだけで触らない
//
// 個々のサーバーの失敗では止まらず、最後にまとめて返す。
func (d *Daemon) Sync(ctx context.Context) error {
	rootless, err := d.eng.Podman.Rootless(ctx)
	if err != nil {
		return fmt.Errorf("check podman: %w", err)
	}
	if !rootless {
		return ErrNotRootless
	}

	servers, err := d.store.List(ctx)
	if err != nil {
		return err
	}

	var errs []error
	changed := false
	for _, s := range servers {
		c, err := d.eng.Files.Write(d.engineServer(s))
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: write unit file: %w", s.Name, err))
			continue
		}
		changed = changed || c
	}
	if changed {
		if err := d.eng.Units.Reload(ctx); err != nil {
			// 読み直せなければ unit の状態も当てにならないので、ここでやめる。
			return errors.Join(append(errs, fmt.Errorf("reload systemd: %w", err))...)
		}
	}

	for _, s := range servers {
		if s.DesiredState != store.DesiredStateRunning {
			continue
		}
		if err := d.startIfStopped(ctx, s.Name); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", s.Name, err))
		}
	}

	d.warnOrphans(servers)
	return errors.Join(errs...)
}

func (d *Daemon) startIfStopped(ctx context.Context, name string) error {
	unit := engine.UnitName(name)
	st, err := d.eng.Units.Status(ctx, unit)
	if err != nil {
		return fmt.Errorf("get unit status: %w", err)
	}
	if st.State() != engine.StateStopped {
		return nil
	}
	slog.Info("starting server that should be running", "server", name)
	if err := d.eng.Units.Start(ctx, unit); err != nil {
		return fmt.Errorf("start unit: %w", err)
	}
	return nil
}

func (d *Daemon) warnOrphans(servers []store.Server) {
	names, err := d.eng.Files.List()
	if err != nil {
		slog.Warn("failed to list unit files", "error", err)
		return
	}
	known := make(map[string]bool, len(servers))
	for _, s := range servers {
		known[s.Name] = true
	}
	for _, name := range names {
		if !known[name] {
			slog.Warn("unit file generated by mcctld has no server in the store; leaving it untouched",
				"server", name, "file", engine.ContainerFileName(name))
		}
	}
}
